package leader_protocol

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"pqgch/gake"
	"pqgch/util"
	"slices"
)

// CryptoSession contains the cryptographic data used for computing the main session key.
type CryptoSession struct {
	TkRight      []byte               // 2-AKE temporary material.
	EskaRight    []byte               // 2-AKE temporary material.
	KeyLeft      [gake.SsLen]byte     // Shared secret with the left neighbor.
	KeyRight     [gake.SsLen]byte     // Shared secret with the right neighbor.
	Xs           [][gake.SsLen]byte   // Xs - each Xi is the result of XOR-ing the left and right key of each protocol participant.
	Commitments  [][32]byte           // The commitment is a result of hashing the Xi and Ri together. They are then broadcasted by each participant.
	Rs           [][gake.CoinLen]byte // Rs - each Ri is randomly generated by each participant.
	SharedSecret [gake.SsLen]byte     // The resulting main session key used for inter-cluster communication.
}

func NewCryptoSession(config util.LeaderConfig) CryptoSession {
	return CryptoSession{
		Xs:          make([][gake.SsLen]byte, len(config.Addrs)),
		Commitments: make([][32]byte, len(config.Addrs)),
		Rs:          make([][gake.CoinLen]byte, len(config.Addrs)),
	}
}

// Session contains selected transport, config and cryptographic session state.
type Session struct {
	receiveChan      chan util.Message
	sender           util.MessageSender
	config           util.LeaderConfig
	crypto           CryptoSession
	onMainSessionKey func() // Callback to be called when the main session key is established.
}

// Create a new Cluster Leader session. This is the session that is used for interacting between cluster leaders.
// It does not take the cluster members into account.
// The Transport defines how the messages produced by the protocol will be routed.
func NewSession(sender util.MessageSender, config util.LeaderConfig, onMainSessionKey func(), receiveChan chan util.Message) *Session {
	s := &Session{
		receiveChan:      receiveChan,
		sender:           sender,
		crypto:           NewCryptoSession(config),
		config:           config,
		onMainSessionKey: onMainSessionKey,
	}

	return s
}

func (s *Session) GetKeyRef() *[32]byte {
	return &s.crypto.SharedSecret
}

// Initialize the session by sending the first message of the 2-AKE to the neighbor.
func (s *Session) Init() {
	if s.config.IsRightQKDPath() {
		rightKeyQKD := s.config.RightQKDKey()
		s.crypto.KeyRight = rightKeyQKD
	}

	if s.config.IsLeftQKDPath() {
		leftKeyQKD := s.config.LeftQKDKey()
		s.crypto.KeyLeft = leftKeyQKD
	}

	msg := s.checkLeftRightKeys()
	if !msg.IsEmpty() {
		s.sender.Send(msg)
	}

	if !s.config.IsRightQKDUrl() && !s.config.IsRightQKDPath() {
		var akeSendARight []byte
		akeSendARight, s.crypto.TkRight, s.crypto.EskaRight = gake.KexAkeInitA(s.config.RightPublicKey())

		msg := util.Message{
			ID:         util.UniqueID(),
			SenderID:   s.config.Index,
			SenderName: s.config.Name(),
			Type:       util.LeadAkeOneMsg,
			ReceiverID: s.config.RightIndex(),
			Content:    base64.StdEncoding.EncodeToString(akeSendARight),
		}

		s.sender.Send(msg)
	}
}

func (s *Session) MessageHandler() {
	for msg := range s.receiveChan {
		s.handleMessage(msg)
	}
}

// Process the first message of 2-AKE, holding as a result keyLeft. The second message of 2-AKE is then sent.
// If we have both keyLeft and keyRight available at this point, the Xi value is calculated and broadcasted.
func (s *Session) onAkeOne(recv util.Message) {
	akeSendA, err := base64.StdEncoding.DecodeString(recv.Content)
	if err != nil {
		util.PrintLine("[ERROR] Invalid base64 content received")
		return
	}

	var akeSendB []byte
	akeSendB, s.crypto.KeyLeft = gake.KexAkeSharedB(
		akeSendA,
		s.config.GetSecretKey(),
		s.config.LeftPublicKey())
	util.PrintLine("[CRYPTO] Established 2-AKE shared key with left neighbor")

	msg := util.Message{
		ID:         util.UniqueID(),
		SenderID:   s.config.Index,
		SenderName: s.config.Name(),
		Type:       util.LeadAkeTwoMsg,
		ReceiverID: recv.SenderID,
		Content:    base64.StdEncoding.EncodeToString(akeSendB),
	}
	s.sender.Send(msg)

	msg = s.checkLeftRightKeys()
	if !msg.IsEmpty() {
		s.sender.Send(msg)
	}
}

// Process the second message of 2-AKE, holding as a result keyRight.
// If we have both keyLeft and keyRight available at this point, the Xi value is calculated and broadcasted.
func (s *Session) onAkeTwo(recv util.Message) {
	akeSendB, err := base64.StdEncoding.DecodeString(recv.Content)
	if err != nil {
		util.PrintLine("[ERROR] Invalid base64 content received")
		return
	}

	s.crypto.KeyRight = gake.KexAkeSharedA(akeSendB, s.crypto.TkRight, s.crypto.EskaRight, s.config.GetSecretKey())

	util.PrintLine("[CRYPTO] Established 2-AKE shared key with right neighbor")

	msg := s.checkLeftRightKeys()
	if !msg.IsEmpty() {
		s.sender.Send(msg)
	}
}

// Handle the message containing Xi, Ri and Commitment. This message is broadcasted by the other protocol participants to everyone else.
// If we receive such a message, we need to try finalizing the protocol, as we could have received the last message of this kind we need.
func (s *Session) onXiRiCommitment(recv util.Message) {
	decoded, err := base64.StdEncoding.DecodeString(recv.Content)
	if err != nil {
		util.PrintLine("[ERROR] Invalid base64 content received")
		return
	}

	s.crypto.Xs[recv.SenderID] = [gake.SsLen]byte(decoded[:gake.SsLen])
	s.crypto.Commitments[recv.SenderID] = [32]byte(decoded[gake.SsLen : 2*gake.SsLen])
	s.crypto.Rs[recv.SenderID] = [gake.CoinLen]byte(decoded[2*gake.SsLen:])

	s.tryFinalizeProtocol()
}

func (s *Session) onLeftKey(recv util.Message) {
	decoded, err := base64.StdEncoding.DecodeString(recv.Content)
	if err != nil || len(decoded) < gake.SsLen {
		util.PrintLine("[ERROR] Invalid base64 content received")
		return
	}
	copy(s.crypto.KeyLeft[:], decoded)

	msg := s.checkLeftRightKeys()
	if !msg.IsEmpty() {
		s.sender.Send(msg)
	}
}

func (s *Session) onRightKey(recv util.Message) {
	decoded, err := base64.StdEncoding.DecodeString(recv.Content)
	if err != nil || len(decoded) < gake.SsLen {
		util.PrintLine("[ERROR] Invalid base64 content received")
		return
	}

	copy(s.crypto.KeyRight[:], decoded)

	msg := s.checkLeftRightKeys()
	if !msg.IsEmpty() {
		s.sender.Send(msg)
	}
}

// Handle the received message according to its type.
func (s *Session) handleMessage(recv util.Message) {
	switch recv.Type {
	case util.LeadAkeOneMsg:
		s.onAkeOne(recv)
	case util.LeadAkeTwoMsg:
		s.onAkeTwo(recv)
	case util.LeaderXiRiCommitmentMsg:
		s.onXiRiCommitment(recv)
	case util.QKDLeftKeyMsg:
		s.onLeftKey(recv)
	case util.QKDRightKeyMsg:
		s.onRightKey(recv)
	default:
		util.PrintLine("[ERROR] Unknown message type encountered")
	}
}

// Check whether we have both keyLeft and keyRight available. If so, compute the Xi, Ri and Commitment message and return it.
// Also, try finalizing the protocol now, since the Xi we computed could have been the last one we needed.
func (s *Session) checkLeftRightKeys() util.Message {
	if s.crypto.KeyRight != [gake.SsLen]byte{} && s.crypto.KeyLeft != [gake.SsLen]byte{} {
		util.PrintLine("[CRYPTO] Established 2-AKE shared keys with both neighbors")
		msg := s.getXiRiCommitmentMsg()
		s.tryFinalizeProtocol()
		return msg
	}

	return util.Message{}
}

// Computation of the Xi, Ri and Commitment message.
// We XOR together our keyLeft and keyRight.
// Generate a random Ri.
// Compute the commitment as a hash of Xi and Ri.
// Save the values for our use and also return a message containing them, so we can send it to other protocol participants.
func (s *Session) getXiRiCommitmentMsg() util.Message {
	xi := gake.XorKeys(s.crypto.KeyRight, s.crypto.KeyLeft)
	ri := gake.GetRi()
	x := append(xi[:], ri[:]...)
	commitment := sha256.Sum256(x)

	s.crypto.Xs[s.config.Index] = xi
	s.crypto.Commitments[s.config.Index] = commitment
	s.crypto.Rs[s.config.Index] = ri

	content := append(append(xi[:], commitment[:]...), ri[:]...)
	msg := util.Message{
		ID:         util.UniqueID(),
		SenderID:   s.config.Index,
		SenderName: s.config.Name(),
		Type:       util.LeaderXiRiCommitmentMsg,
		Content:    base64.StdEncoding.EncodeToString(content),
	}

	return msg
}

// First, we check whether we have received all of the Xs.
// Then, we check whether XOR-ing the Xs together gives use the zero byte array.
// Then, we check the commitments by recalculating them.
// Then, we construct the party identifiers array.
// Finally we compute the shared secret key and session ID. We save it for later use - broadcasting it to the cluster members.
func (s *Session) tryFinalizeProtocol() {
	if slices.Contains(s.crypto.Xs, [gake.SsLen]byte{}) {
		return
	}
	util.PrintLine("[CRYPTO] Received all Xs")

	for i, x := range s.crypto.Xs {
		util.PrintLine(fmt.Sprintf("[CRYPTO] X%d: %02x", i, x[:4]))
	}

	ok := util.CheckXs(s.crypto.Xs, len(s.config.Addrs))
	if !ok {
		util.ExitWithMsg("Failed XS check")
	}
	util.PrintLine("[CRYPTO] Xs check: success")

	ok = checkCommitments(len(s.config.Addrs), s.crypto.Xs, s.crypto.Rs, s.crypto.Commitments)
	if !ok {
		util.ExitWithMsg("Failed Commitments check")
	}
	util.PrintLine("[CRYPTO] Commitments check: success")

	PIDs := make([][gake.PidLen]byte, len(s.config.Addrs))
	for i, n := range s.config.Addrs {
		var byteArr [gake.PidLen]byte
		copy(byteArr[:], []byte(n))
		PIDs[i] = byteArr
	}

	otherLeftKeys := util.ComputeAllLeftKeys(len(s.config.Addrs), s.config.Index, s.crypto.KeyLeft, s.crypto.Xs, PIDs)
	sharedSecret := computeSharedSecret(otherLeftKeys, PIDs, len(s.config.Addrs))

	util.PrintLine(fmt.Sprintf("[CRYPTO] Main Session Key established: %02x...", sharedSecret[:4]))

	s.crypto.SharedSecret = sharedSecret
	s.onMainSessionKey()
}

// Compute the shared secret from the left keys of the protocol participants.
// Note that the session key itself is computed from the first numParties - 1 left keys.
// NOTE: we do not compute the Session ID (sid), since we do not use it.
func computeSharedSecret(otherLeftKeys [][32]byte, pids [][20]byte, numParties int) [32]byte {
	// For the session key, we use the left keys of protocol participants 0..n-2, so we skip one.
	sessionKeyTemp := make([]byte, 32*(numParties-1)+20*numParties)
	for i := range numParties - 1 {
		copy(sessionKeyTemp[i*32:(i+1)*32], otherLeftKeys[i][:])
	}
	for i := range numParties - 1 {
		copy(sessionKeyTemp[(numParties-1)*32+i*20:(numParties-1)*32+(i+1)*20], pids[i][:])
	}

	sessionKey := sha256.Sum256(sessionKeyTemp)

	return sessionKey
}

// We have received the commitments from other protocol participants. We also have received Rs and Xs from them.
// Now, check whether by recalculating the commitments from the Rs and Xs we get the same values.
func checkCommitments(
	numParties int,
	xs [][32]byte,
	rs [][44]byte,
	commitments [][32]byte) bool {
	for i := range numParties {
		x := append(xs[i][:], rs[i][:]...)
		commitment := sha256.Sum256(x)

		for j := range 32 {
			if commitment[j] != commitments[i][j] {
				return false
			}
		}
	}

	return true
}
